url: https://seungwongit.github.io
baseurl: /devblog/

# Site settings
title: DEV BLOG
email: tmddnjs710@naver.com
description: "Welcome to my development blog. I will always try to learn."


# Team names, titles and social links
people:

- name: #

- name: Seung Won, Choi
  pic: 1
  position: Web Designer & publisher
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
      
      
- name: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: #
  - title: stack-overflow
    url: #
    # http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: #
    # http://bitbucket.org/jekyll
  - title: github
    url: #
    # http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: #
  # 3481 Melrose Place
  - line: #
  # Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
